/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progettodb;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author cucchiarini.cesare
 */
public class FrameProgetto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameProgetto.class.getName());
    
    private DefaultListModel<String> modelStudenti;
    private DefaultComboBoxModel<String> modelClassi;
    /**
     * Creates new form FrameProgetto
     */
    public FrameProgetto() {
        initComponents();
        
        this.setLayout(new BorderLayout());
        
        JPanel panel  = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        
        modelClassi = new DefaultComboBoxModel();
        JComboBox boxClassi = new JComboBox(modelClassi);
        boxClassi.setBorder(BorderFactory.createEmptyBorder(0, 300, 0, 300));
        boxClassi.addActionListener(new ActionListener(){
            @Override 
            public void actionPerformed(ActionEvent e){
                modelStudenti.clear();
                modelStudenti.addAll(DBManager.leggiStudenti(((String)boxClassi.getSelectedItem()).substring(0, 2)));
            }
        });
        
        modelStudenti = new DefaultListModel();
        JList listStudenti = new JList(modelStudenti);
        
        JScrollPane scrollPane = new JScrollPane(listStudenti);
        scrollPane.setBorder(BorderFactory.createEmptyBorder(0, 500, 0, 500));
        
        panel.add(Box.createVerticalGlue());
        panel.add(boxClassi);
        panel.add(Box.createVerticalGlue());
        panel.add(scrollPane);
        panel.add(Box.createVerticalGlue());
        
        this.add(panel, BorderLayout.CENTER);
        
        modelClassi.addAll(DBManager.leggiClassi());
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameProgetto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
